/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QaFocusRouteImport } from './routes/qa.focus'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'

const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QaFocusRoute = QaFocusRouteImport.update({
  id: '/qa/focus',
  path: '/qa/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enquiry': typeof EnquiryRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/qa/focus': typeof QaFocusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enquiry': typeof EnquiryRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/qa/focus': typeof QaFocusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enquiry': typeof EnquiryRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/login': typeof AdminLoginRoute
  '/qa/focus': typeof QaFocusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enquiry' | '/admin/inbox' | '/admin/login' | '/qa/focus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enquiry' | '/admin/inbox' | '/admin/login' | '/qa/focus'
  id:
    | '__root__'
    | '/'
    | '/enquiry'
    | '/admin/inbox'
    | '/admin/login'
    | '/qa/focus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnquiryRoute: typeof EnquiryRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLoginRoute: typeof AdminLoginRoute
  QaFocusRoute: typeof QaFocusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa/focus': {
      id: '/qa/focus'
      path: '/qa/focus'
      fullPath: '/qa/focus'
      preLoaderRoute: typeof QaFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnquiryRoute: EnquiryRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLoginRoute: AdminLoginRoute,
  QaFocusRoute: QaFocusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
